# Generated by Django 4.2 on 2024-07-28 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSamuel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='titulo',
            new_name='categoria',
        ),
    ]
